site_name: Nightscout - Xdrip - AndroidAPS
site_url: https://atlas-night-out.github.io/Nightscout-xdrip-AAPS

theme:
  name: material
  font:
    text: Merriweather
    code: Red Hat Mono
  logo: assets/xDrip+logo.png
  favicon: assets/favicon.ico

  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: white
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: black
      accent: deep orange

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details 

  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  

nav:
- Home: 'index.md'
- Dexcom :
        - 'Dexcom G6/One': 'user-guide/Dexcom/Dexcom G6_One.md'
        - 'Dexcom xDrip Recommended Settings': 'user-guide/Dexcom/xDrip-Advised-Settings - G6, G7,Dexcom One,One+.md'
        - 'Starting a G7 or One+': 'user-guide/Dexcom/Starting a G7 or One.md'

- Xdrip :
    - 'Xdrip+ Intro': 'user-guide/xdrip/xdrip - Intro.md'
    - 'Download': 'user-guide/xdrip/xdrip - Download.md'
    - 'Install': 'user-guide/xdrip/xdrip - install.md'        
    - 'Connection issues – How to Fix': 'user-guide/xdrip/Xdrip connection Problem fix.md'

-   Watches:
    - 'Watches Intro': 'user-guide/Watches/Watches Intro.md'

-   T1's Smart Home:
    - 'Aqara T1 Pro cube Setup to Echo Show': 'user-guide/Alexa/T1_Pro_Cube/Aqara T1 Pro cube Setup to Echo Show.md'
    - 'Add Nightscout onto an Echo Show': 'user-guide/Alexa/T1_Pro_Cube/Aexa Show Nightscout on Echo Show 10 3rd Gen.md'
    - 'Myjade Aqara Cube T1 Pro Setup for T1’s to Echo Show 10': 'user-guide/Alexa/T1_Pro_Cube/Myjade Aqara Cube T1 Pro Setup for T1’s.md'
    - 'LinknLink': 'user-guide/LinknLink/LinknLink.md'
-   Freestyle Libre : 
    - 'Setup Freestyle Libre 2': 'user-guide/FreestyleLibre/How_to_setup_FreeStyle_Libre_2.md'    


-   AndroidAPS : 
    - 'What is AAPS': 'user-guide/AndroidAPS/What is AAPS.md'
    - 'AAPS on Wear OS Smartwatch': 'user-guide/AndroidAPS/Bolus in Watch for AAPS Bolus.md'

-   Medtronic :
    - 'Disclaimer and Warning': 'user-guide/Medtronic/Disclaimer and Warning.md'
    - 'New experimental version for CareLink reCAPTCHA': 'user-guide/Medtronic/New experimental version for CareLink reCAPTCHA.md'

- Helpful Things : 
    - 'Helpful Links': 'user-guide/Helpful/Helplinks.md'
    - 'Github - Deleting-your-cgm-remote-monitor  ': 'user-guide/Helpful/Deleting-your-cgm-remote-monitor.md' 
    - 'About': 'user-guide/Helpful/about.md'




    

      

extra:
  social:
    - icon: simple/youtube
      link: https://studio.youtube.com/channel/UC9TwtBefjjKw_uKHiIWMkBA
    - icon: simple/linkedin
      link: https://linkedin.com/in/willettjames
  
  copyright: Copyright &copy; 2024 D.Galloway
  generator: false



  
  