site_name: Nightscout - Xdrip - AndroidAPS
site_url: https://sitename.example.com

theme:
  name: material
  font:
    text: Merriweather
    code: Red Hat Mono
  icon:
   logo: fontawesome/solid/W


  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: white
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: black
      accent: deep orange


markdown_extensions:
   - attr_list
   - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  generator: false