site_name: Nightscout - Xdrip - AndroidAPS
site_url: https://atlas-night-out.github.io/Nightscout-xdrip-AAPS

theme:
  name: material
  font:
    text: Merriweather
    code: Red Hat Mono
  logo: assets/xDrip+logo.png
  favicon: assets/favicon.ico

  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: white
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: black
      accent: deep orange

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details 

  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
- Home: 'index.md'
- Dexcom :
        - 'Dexcom G6/One': 'user-guide/Dexcom/Dexcom G6_One.md'
        - 'Dexcom xDrip Recommended Settings': 'user-guide/Dexcom/xDrip-Advised-Settings - G6, G7,Dexcom One,One+.md'
        - 'Starting a G7 or One+': 'user-guide/Dexcom/Starting a G7 or One.md'
        

- Helpful Things : 
    - 'Helpful Links': 'user-guide/Helpful/Helplinks.md'
    - 'Github - Deleting-your-cgm-remote-monitor  ': 'user-guide/Helpful/Deleting-your-cgm-remote-monitor.md' 
    - 'About': 'about.md'

- Diagram-Examples :
    - 'Content Tabs': 'user-guide/Diagram-Examples/content-tabs.md'
    - 'Flowchart': 'user-guide/Diagram-Examples/flowchart example.md'
    - 'Code-Examples': 'user-guide/Diagram-Examples/code-examples.md'
    - 'Admonitions': 'user-guide/Diagram-Examples/admonitions.md'
    - 'Diagram-Examples': 'user-guide/Diagram-Examples/diagram-examples.md'

      

extra:
  social:
    - icon: simple/youtube
      link: https://studio.youtube.com/channel/UC9TwtBefjjKw_uKHiIWMkBA
    - icon: simple/linkedin
      link: https://linkedin.com/in/willettjames
  
  copyright: Copyright &copy; 2024 D.Galloway
  generator: false



  
  