site_name: Nightscout - Xdrip - AndroidAPS
site_url: https://atlas-night-out.github.io/Nightscout-xdrip-AAPS

theme:
    name: material
    font:
      text: Merriweather
      code: Red Hat Mono
    logo: assets/xDrip+logo.png
    favicon: assets/favicon.ico

    features:
      - navigation.footer
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.top

    palette:
      # Dark Mode
      - scheme: slate
        toggle:
          icon: material/weather-sunny
          name: Dark mode
        primary: white
        accent: deep purple

      # Light Mode
      - scheme: default
        toggle:
          icon: material/weather-night
          name: Light mode
        primary: black
        accent: deep orange

plugins:
  - search
  - git-authors:
        exclude:
            - index.md
  - git-revision-date-localized:
      type: timeago
      timezone: Europe/london
      locale: en
      fallback_to_build_date: false
      enable_creation_date: true

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/public-profile/settings?trk=d_flagship3_profile_self_view_public_profile
    - icon: fontawesome/brands/twitter
      link: https://x.com/T1AtlasNightOut
    - icon: fontawesome/brands/github
      link: https://github.com/Atlas-Night-Out/xdrip-Nightscout-AAPS
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC9TwtBefjjKw_uKHiIWMkBA?sub_confirmation=1
      
      


  copyright: Copyright &copy; 2025 D. Gall
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details 

  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  

nav:
- Home: 'index.md'
- Dexcom :
        - 'Dexcom G6/One': 'user-guide/Dexcom/Dexcom G6_One.md'
        - 'Dexcom xDrip Recommended Settings': 'user-guide/Dexcom/Dexcom xDrip Recommended Settings.md'
        - 'Starting a G7 or One+': 'user-guide/Dexcom/Starting a G7 or One.md'
        - 'Dex Share Followers': 'user-guide/Dexcom/Dex Share Followers.md'
        

- Xdrip :
    - 'Xdrip+ Intro': 'user-guide/xdrip/xdrip - Intro.md'
    - 'Download': 'user-guide/xdrip/xdrip - Download.md'
    - 'Install': 'user-guide/xdrip/xdrip - install.md'        
    - 'Connection issues – How to Fix': 'user-guide/xdrip/Xdrip connection Problem fix.md'
    - 'Hardware Data Source': 'user-guide/xdrip/xdrip - hardwaredatasource.md'
    - 'xDrip Settings': 'user-guide/xdrip/settings.md'
    - 'Display Settings': 'user-guide/xdrip/Display-Settings.md'
    
    - 'Tidepool': 'user-guide/xdrip/Tidepool.md'

- Nightscout :
    - 'Part 1 Setting up Github Account': 'user-guide/Nightscout/Setting_up_Github_Account_part1.md'

-   Watches:
    - 'Watches Intro': 'user-guide/Watches/Watches Intro.md'
    - 'All Watch Types': 'user-guide/Watches/Watches.md'

-   T1's Smart Home:
    
    - 'Add Nightscout onto an Echo Show': 'user-guide/Alexa/T1_Pro_Cube/Alexa Show Nightscout on Echo Show 10 3rd Gen.md'
    - 'My Jade Aqara Cube T1 Pro Setup for T1’s to Echo Show 10': 'user-guide/Alexa/T1_Pro_Cube/Myjade Aqara Cube T1 Pro Setup for T1’s.md'
    
-   Freestyle Libre : 
    - 'Setup Freestyle Libre 2': 'user-guide/FreestyleLibre/How_to_setup_FreeStyle_Libre_2.md'    


-   AndroidAPS : 
    - 'What is AAPS': 'user-guide/AndroidAPS/What is AAPS.md'
    

-   Medtronic :
    - 'Disclaimer and Warning': 'user-guide/Medtronic/Disclaimer and Warning.md'
    - 'New experimental version for CareLink reCAPTCHA': 'user-guide/Medtronic/New experimental version for CareLink reCAPTCHA.md'

- Helpful Things : 
    - 'Helpful Links': 'user-guide/Helpful/Helplinks.md'
    - 'Github - Deleting-your-cgm-remote-monitor  ': 'user-guide/Helpful/Deleting-your-cgm-remote-monitor.md' 
    - 'About': 'user-guide/Helpful/about.md'

- Diagram-Examples :
    - 'Content Tabs': 'user-guide/Diagram-Examples/content-tabs.md'
    - 'Flowchart': 'user-guide/Diagram-Examples/flowchart example.md'
    - 'Code-Examples': 'user-guide/Diagram-Examples/code-examples.md'
    - 'Admonitions': 'user-guide/Diagram-Examples/admonitions.md'
    - 'Diagram-Examples': 'user-guide/Diagram-Examples/diagram-examples.md'






    

      





  
  